CREATE TABLE students AS
   SELECT "2019/08/06 4:19:18 PM MDT" AS time, 21 AS number, "blue" AS color, "Choose this option instead" AS seven, "Bohemian Rhapsody by Queen" as song, "12-25" as date, "lion" as pet, "5" AS instructor, 123 AS smallest UNION
   SELECT "2019/08/06 4:20:15 PM MDT"  , 52          , "red"                      , "You're not the boss of me!", "Despacito"                , "07-15", "anteater"                                                                             , "1"      , 14                    UNION
   SELECT "2019/08/06 4:21:05 PM MDT"  , 19          , "purple"                   , "the number 7 below."       , "Despacito"                , "01-17", "corgi"                                                                                , "2"      , 17                    UNION
   SELECT "2019/08/06 4:21:53 PM MDT"  , 6           , "aquamarine"               , "the number 7 below."       , "Clair De Lune"            , "11-29", "red panda"                                                                            , "5"      , 17                    UNION
   SELECT "2019/08/06 4:22:45 PM MDT"  , 17          , "lavender"                , "the number 7 below."       , "Electric Feel"            , "01-01", "a lion"                                                                               , "1"      , 1                     UNION
   SELECT "2019/08/06 4:22:54 PM MDT"  , 6           , "blue"                     , "7"                         , "Bohemian Rhapsody"        , "04-04", "my god"                                                                               , "4"      , 32                    UNION
   SELECT "2019/08/06 4:22:56 PM MDT"  , 1           , "white"                    , "7"                         , "All I want for Christmas" , "08-12", "none"                                                                                 , "2"      , 4                     UNION
   SELECT "2019/08/06 4:23:20 PM MDT"  , 56          , "purple"                   , "7"                         , "Bohemian Rhapsody"        , "06-24", "raccoon"                                                                              , "2"      , 33                    UNION
   SELECT "2019/08/06 4:23:56 PM MDT"  , 73          , "blue"                     , "the number 7 below."       , "Despacito"                , "12-27", "golden retriever"                                                                     , "6"      , 37                    UNION
   SELECT "2019/08/06 4:25:05 PM MDT"  , 9           , "black"                    , "Choose this option instead", "Bohemian Rhapsody"        , "07-10", "golden retriever"                                                                     , "2"      , 1                     UNION
   SELECT "2019/08/06 4:25:54 PM MDT"  , 2           , "orange"                   , "Choose this option instead", "Clair De Lune"            , "01-01", "deer"                                                                                 , "2"      , 8                     UNION
   SELECT "2019/08/06 4:27:13 PM MDT"  , 21          , "blue"                     , "the number 7 below."       , "Clair De Lune"            , "11-21", "cheetah"                                                                              , "1"      , 1                     UNION
   SELECT "2019/08/06 4:28:41 PM MDT"  , 12          , "white"                    , "7"                         , "All I want for Christmas" , "08-12", "dog"                                                                                  , "6"      , 1                     UNION
   SELECT "2019/08/06 4:29:53 PM MDT"  , 66          , "light blue"               , "7"                         , "All I want for Christmas" , "08-07", "dog"                                                                                  , "5"      , 1                     UNION
   SELECT "2019/08/06 4:30:02 PM MDT"  , 12          , "blue"                    , "the number 7 below."       , "Bohemian Rhapsody"        , "07-12", "dire wolf"                                                                           , "6"      , 999999999999999999    UNION
   SELECT "2019/08/06 4:30:17 PM MDT"  , 3           , "blue"                     , "Choose this option instead", "All I want for Christmas" , "09-07", "kangaroo"                                                                            , "6"      , 7                     UNION
   SELECT "2019/08/06 4:31:10 PM MDT"  , 27          , "dark white"               , "7"                         , "Bohemian Rhapsody"        , "06-20", "cat"                                                                                  , "6"      , 19                    UNION
   SELECT "2019/08/06 4:31:47 PM MDT"  , 50          , "blue"                     , "7"                         , "Clair De Lune"            , "08-14", "dog"                                                                                  , "5"      , 41                    UNION
   SELECT "2019/08/06 4:31:57 PM MDT"  , 7           , "blue"                     , "the number 7 below."       , "Bohemian Rhapsody"        , "09-14", "dog"                                                                                  , "1"      , 1                     UNION
   SELECT "2019/08/06 4:32:30 PM MDT"  , 42          , "black"                    , "7"                         , "Clair De Lune"            , "06-09", "a honda civic"                                                                        , "2"      , 1                     UNION
   SELECT "2019/08/06 4:32:49 PM MDT"  , 7           , "blue"                     , "7"                         , "Bohemian Rhapsody"        , "07-28", "bear"                                                                                 , "6"      , 42                    UNION
   SELECT "2019/08/06 4:33:12 PM MDT"  , 18          , "blue"                     , "7"                         , "Despacito"                , "12-25", "pig"                                                                                 , "6"      , 29                    UNION
   SELECT "2019/08/06 4:33:47 PM MDT"  , 21          , "blue"                     , "the number 7 below."       , "Despacito"                , "02-18", "a fox"                                                                                , "6"      , 21                    UNION
   SELECT "2019/08/06 4:37:07 PM MDT"  , 99          , "light gray"               , "the number 7 below."       , "Bohemian Rhapsody"        , "08-03", "dog"                                                                                  , "6"      , 9                     UNION
   SELECT "2019/08/06 4:39:21 PM MDT"  , 1           , "black"                    , "the number 7 below."       , "Old Town Road"            , "09-10", "unicorn"                                                                              , "6"      , 1                     UNION
   SELECT "2019/08/06 4:41:26 PM MDT"  , 47          , "sunset"                   , "7"                         , "Electric Feel"            , "04-07", "falcon"                                                                               , "4"      , 11                    UNION
   SELECT "2019/08/06 4:42:01 PM MDT"  , 7           , "mauve"                    , "the number 7 below."       , "Bohemian Rhapsody"        , "06-22", "bunny"                                                                                , "2"      , 17                    UNION
   SELECT "2019/08/06 4:42:48 PM MDT"  , 99          , "baby pink"                , "You're not the boss of me!", "Clair De Lune"            , "07-16", "panda bear"                                                                           , "2"      , 20                    UNION
   SELECT "2019/08/06 4:47:30 PM MDT"  , 91          , "turquoise"                , "7"                         , "All I want for Christmas" , "08-12", "turtle"                                                                               , "6"      , 53                    UNION
   SELECT "2019/08/06 4:49:56 PM MDT"  , 11          , "purple"                   , "the number 7 below."       , "All I want for Christmas" , "01-01", "cat"                                                                                  , "2"      , 43                    UNION
   SELECT "2019/08/06 4:50:46 PM MDT"  , 19          , "blue"                     , "7"                         , "Clair De Lune"            , "06-07", "panda"                                                                                , "2"      , 17                    UNION
   SELECT "2019/08/06 4:50:48 PM MDT"  , 72          , "lavender"                 , "7"                         , "Bohemian Rhapsody"        , "08-06", "dog"                                                                                  , "5"      , 17                    UNION
   SELECT "2019/08/06 4:52:02 PM MDT"  , 19          , "blue"                     , "the number 7 below."       , "Despacito"                , "09-05", "pig"                                                                                  , "2"      , 1                     UNION
   SELECT "2019/08/06 4:52:38 PM MDT"  , 75          , "red"                      , "Choose this option instead", "Despacito"                , "02-16", "penguin"                                                                              , "6"      , 1                     UNION
   SELECT "2019/08/06 4:54:35 PM MDT"  , 13          , "blue"                     , "the number 7 below."       , "All I want for Christmas" , "12-25", "toucan"                                                                               , "6"      , 4                     UNION
   SELECT "2019/08/06 4:57:23 PM MDT"  , 69          , "blurple"                  , "You're not the boss of me!", "Clair De Lune"            , "06-09", "greninja"                                                                             , "6"      , 1                     UNION
   SELECT "2019/08/06 4:59:50 PM MDT"  , 64          , "blue"                     , "You're not the boss of me!", "All I want for Christmas" , "05-30", "owl"                                                                                  , "6"      , 36                    UNION
   SELECT "2019/08/06 5:02:14 PM MDT"  , 99          , "blue"                     , "7"                         , "All I want for Christmas" , "12-07", "golden retriever"                                                                     , "6"      , 1                     UNION
   SELECT "2019/08/06 5:03:53 PM MDT"  , 12          , "blue"                     , "the number 7 below."       , "Electric Feel"            , "11-11", "galápagos tortoise"                                                                   , "6"      , 2                     UNION
   SELECT "2019/08/06 5:04:52 PM MDT"  , 9           , "red"                      , "seven"                     , "Bohemian Rhapsody"        , "07-09", "pig"                                                                                  , "5"      , 1                     UNION
   SELECT "2019/08/06 5:05:40 PM MDT"  , 69          , "black"                    , "You're not the boss of me!", "Bohemian Rhapsody"        , "06-09", "sharks with frickin lasers"                                                           , "6"      , 69                    UNION
   SELECT "2019/08/06 5:13:40 PM MDT"  , 69          , "blue"                     , "the number 7 below."       , "Bohemian Rhapsody"        , "04-20", "koala"                                                                                , "6"      , 1                     UNION
   SELECT "2019/08/06 5:13:55 PM MDT"  , 13          , "smokey topaz"             , "the number 7 below."       , "Despacito"                , "11-11", "horse"                                                                                , "5"      , 8                     UNION
   SELECT "2019/08/06 5:20:28 PM MDT"  , 69          , "red"                      , "7"                         , "Bohemian Rhapsody"        , "12-20", "cat"                                                                                  , "2"      , 1                     UNION
   SELECT "2019/08/06 5:21:03 PM MDT"  , 37          , "royal blue"               , "Choose this option instead", "Bohemian Rhapsody"        , "03-17", "dog"                                                                                  , "5"      , 17                    UNION
   SELECT "2019/08/06 5:24:43 PM MDT"  , 6           , "blue"                     , "the number 7 below."       , "Bohemian Rhapsody"        , "03-30", "alien"                                                                                , "2"      , 6                     UNION
   SELECT "2019/08/06 5:27:40 PM MDT"  , 25          , "red"                      , "You're not the boss of me!", "Bohemian Rhapsody"        , "08-08", "human"                                                                                , "2"      , 1                     UNION
   SELECT "2019/08/06 5:27:47 PM MDT"  , 87          , "red"                      , "You're not the boss of me!", "Old Town Road"            , "04-20", "tiger"                                                                                , "6"      , 41                    UNION
   SELECT "2019/08/06 5:29:23 PM MDT"  , 22          , "green"                    , "seven"                     , "Electric Feel"            , "12-24", "saffcon"                                                                              , "2"      , 14                    UNION
   SELECT "2019/08/06 5:32:52 PM MDT"  , 50          , "orange"                   , "7"                         , "Old Town Road"            , "06-26", "dragon"                                                                               , "1"      , 8                     UNION
   SELECT "2019/08/06 5:34:22 PM MDT"  , 12          , "blue"                     , "7"                         , "Old Town Road"            , "08-06", "giraffe"                                                                              , "1"      , 12                    UNION
   SELECT "2019/08/06 5:39:08 PM MDT"  , 8           , "green"                    , "the number 7 below."       , "Despacito"                , "03-14", "german shepherd"                                                                      , "6"      , 24                    UNION
   SELECT "2019/08/06 5:43:06 PM MDT"  , 13          , "blue"                     , "Choose this option instead", "Clair De Lune"            , "07-13", "a parrot"                                                                             , "1"      , 7                     UNION
   SELECT "2019/08/06 5:50:30 PM MDT"  , 21          , "periwinkle"               , "7"                         , "Clair De Lune"            , "03-30", "pikachu"                                                                              , "4"      , 1                     UNION
   SELECT "2019/08/06 5:51:50 PM MDT"  , 13          , "blue"                     , "the number 7 below."       , "Bohemian Rhapsody"        , "01-13", "kiwi bot"                                                                             , "6"      , 11                    UNION
   SELECT "2019/08/06 5:54:36 PM MDT"  , 61          , "razzmatazz"               , "the number 7 below."       , "Clair De Lune"            , "08-15", "a dragon"                                                                             , "4"      , 124                   UNION
   SELECT "2019/08/06 5:57:31 PM MDT"  , 84          , "green"                    , "Choose this option instead", "Bohemian Rhapsody"        , "10-09", "flying squirrel"                                                                      , "6"      , 19                    UNION
   SELECT "2019/08/06 6:01:47 PM MDT"  , 69          , "blue"                     , "the number 7 below."       , "Electric Feel"            , "04-20", "cat"                                                                                  , "5"      , 1                     UNION
   SELECT "2019/08/06 6:19:03 PM MDT"  , 27          , "light blue"               , "the number 7 below."       , "Clair De Lune"            , "09-27", "shiba"                                                                               , "5"      , 17                    UNION
   SELECT "2019/08/06 6:19:24 PM MDT"  , 88          , "blue"                     , "seven"                     , "Despacito"                , "08-20", "rabbit"                                                                               , "5"      , 2                     UNION
   SELECT "2019/08/06 6:19:44 PM MDT"  , 87          , "blue"                     , "the number 7 below."       , "Clair De Lune"            , "02-24", "corgi"                                                                                , "2"      , 37                    UNION
   SELECT "2019/08/06 6:23:10 PM MDT"  , 10          , "blue"                     , "7"                         , "Bohemian Rhapsody"        , "01-19", "elephant"                                                                            , "6"      , 7                     UNION
   SELECT "2019/08/06 6:35:56 PM MDT"  , 77          , "green"                    , "7"                         , "All I want for Christmas" , "08-08", "human"                                                                                , "1"      , 10                    UNION
   SELECT "2019/08/06 6:42:38 PM MDT"  , 42          , "blue"                     , "the number 7 below."       , "All I want for Christmas" , "11-25", "koala"                                                                                , "5"      , 1                     UNION
   SELECT "2019/08/06 6:43:56 PM MDT"  , 5           , "blue"                     , "seven"                     , "Clair De Lune"            , "12-25", "cat"                                                                                  , "1"      , 52                    UNION
   SELECT "2019/08/06 6:47:28 PM MDT"  , 2           , "blue"                     , "the number 7 below."       , "Old Town Road"            , "04-20", "cheetah"                                                                              , "6"      , 1                     UNION
   SELECT "2019/08/06 6:59:14 PM MDT"  , 25          , "orange"                   , "7"                         , "Bohemian Rhapsody"        , "08-16", "dog"                                                                                  , "5"      , 25                    UNION
   SELECT "2019/08/06 7:02:23 PM MDT"  , 88          , "blue"                     , "You're not the boss of me!", "Old Town Road"            , "09-16", "horse"                                                                                , "2"      , 1                     UNION
   SELECT "2019/08/06 7:11:54 PM MDT"  , 16          , "teal"                     , "the number 7 below."       , "Electric Feel"            , "03-24", "dog"                                                                                  , "6"      , 18                    UNION
   SELECT "2019/08/06 7:21:10 PM MDT"  , 24          , "n/a"                      , "7"                         , "Clair De Lune"            , "12-23", "i wouldn't choose any. an animal should be free, like how humans uphold freedom."     , "5"      , 1                     UNION
   SELECT "2019/08/06 7:23:11 PM MDT"  , 7           , "yellow"                   , "the number 7 below."       , "Old Town Road"            , "06-22", "dolphin"                                                                              , "6"      , 1                     UNION
   SELECT "2019/08/06 7:25:22 PM MDT"  , 16          , "pink"                     , "Choose this option instead", "Despacito"                , "03-14", "dog"                                                                                  , "6"      , 6                     UNION
   SELECT "2019/08/06 7:30:00 PM MDT"  , 9           , "red"                      , "the number 7 below."       , "Bohemian Rhapsody"        , "02-29", "cat"                                                                                  , "4"      , 1                     UNION
   SELECT "2019/08/06 7:31:21 PM MDT"  , 42          , "blue"                     , "the number 7 below."       , "Despacito"                , "04-01", "slime"                                                                                , "5"      , 7                     UNION
   SELECT "2019/08/06 7:34:46 PM MDT"  , 6           , "purple"                   , "Choose this option instead", "Old Town Road"            , "06-16", "cat"                                                                                  , "2"      , 1                     UNION
   SELECT "2019/08/06 7:39:13 PM MDT"  , 27          , "blue"                     , "the number 7 below."       , "Bohemian Rhapsody"        , "06-09", "lion"                                                                                 , "6"      , 3                     UNION
   SELECT "2019/08/06 8:17:11 PM MDT"  , 2           , "blue"                     , "7"                         , "Old Town Road"            , "08-16", "dog"                                                                                  , "5"      , 5                     UNION
   SELECT "2019/08/06 8:29:52 PM MDT"  , 93          , "blue"                     , "Choose this option instead", "Despacito"                , "08-06", "douge"                                                                                , "3"      , 1                     UNION
   SELECT "2019/08/06 8:52:25 PM MDT"  , 2           , "blue"                     , "the number 7 below."       , "Electric Feel"            , "06-03", "dog"                                                                                  , "2"      , 1                     UNION
   SELECT "2019/08/06 9:09:30 PM MDT"  , 51          , "blue"                     , "Choose this option instead", "Electric Feel"            , "08-23", "cat"                                                                                  , "1"      , 11                    UNION
   SELECT "2019/08/06 9:12:18 PM MDT"  , 32          , "blue"                     , "the number 7 below."       , "Despacito"                , "07-14", "dog"                                                                                  , "5"      , 73                    UNION
   SELECT "2019/08/06 9:14:27 PM MDT"  , 16          , "green"                    , "seven"                     , "Clair De Lune"            , "02-29", "snake"                                                                                , "5"      , 1                     UNION
   SELECT "2019/08/06 9:31:00 PM MDT"  , 42          , "magenta"                  , "7"                         , "Electric Feel"            , "11-03", "tiger"                                                                                , "6"      , 12                    UNION
   SELECT "2019/08/06 9:33:14 PM MDT"  , 6           , "red"                      , "the number 7 below."       , "Bohemian Rhapsody"        , "10-13", "dog"                                                                                  , "6"      , 1                     UNION
   SELECT "2019/08/06 9:33:47 PM MDT"  , 99          , "blue"                     , "the number 7 below."       , "Bohemian Rhapsody"        , "03-09", "alpaca"                                                                               , "6"      , 13                    UNION
   SELECT "2019/08/06 9:39:40 PM MDT"  , 1           , "white"                    , "7"                         , "Clair De Lune"            , "01-01", "an omniscient being who answers all of my questions cat meow"                         , "1"      , 1                     UNION
   SELECT "2019/08/06 9:49:44 PM MDT"  , 27          , "blue"                     , "Choose this option instead", "All I want for Christmas" , "12-27", "lion"                                                                                 , "6"      , 16                    UNION
   SELECT "2019/08/06 9:58:50 PM MDT"  , 25          , "blue"                     , "7"                         , "Despacito"                , "09-16", "rabbit"                                                                              , "1"      , 1                     UNION
   SELECT "2019/08/06 10:01:57 PM MDT" , 43          , "green"                    , "7"                         , "Old Town Road"            , "10-18", "dog"                                                                                  , "5"      , 12                    UNION
   SELECT "2019/08/06 10:04:43 PM MDT" , 7           , "blue"                     , "Choose this option instead", "All I want for Christmas" , "05-01", "penguin"                                                                              , "2"      , 35                    UNION
   SELECT "2019/08/06 10:17:14 PM MDT" , 19          , "green"                    , "7"                         , "Bohemian Rhapsody"        , "10-31", "a niffler"                                                                            , "6"      , 107                   UNION
   SELECT "2019/08/06 10:23:42 PM MDT" , 12          , "green"                    , "the number 7 below."       , "Bohemian Rhapsody"        , "12-12", "oski the bear"                                                                        , "6"      , 4                     UNION
   SELECT "2019/08/06 10:26:56 PM MDT" , 7           , "magenta"                  , "7"                         , "Clair De Lune"            , "01-01", "cheetah"                                                                              , "6"      , 7                     UNION
   SELECT "2019/08/06 10:34:15 PM MDT" , 99          , "black"                    , "the number 7 below."       , "Despacito"                , "04-15", "lion"                                                                                 , "5"      , 33                    UNION
   SELECT "2019/08/06 10:37:02 PM MDT" , 21          , "black"                    , "7"                         , "Bohemian Rhapsody"        , "02-27", "i don't want a pet."                                                                  , "2"      , 23                    UNION
   SELECT "2019/08/06 10:53:09 PM MDT" , 79          , "maroon"                   , "7"                         , "Clair De Lune"            , "03-14", "chinchilla"                                                                           , "2"      , 6                     UNION
   SELECT "2019/08/06 10:55:38 PM MDT" , 4           , "green"                    , "You're not the boss of me!", "Despacito"                , "02-17", "alex"                                                                                 , "6"      , 4                     UNION
   SELECT "2019/08/06 11:01:55 PM MDT" , 5           , "rainbow"                  , "Choose this option instead", "Despacito"                , "02-11", "beaver"                                                                               , "4"      , 37                    UNION
   SELECT "2019/08/06 11:29:42 PM MDT" , 3           , "pink"                     , "the number 7 below."       , "Despacito"                , "11-01", "blue whale"                                                                           , "6"      , 1                     UNION
   SELECT "2019/08/06 11:48:10 PM MDT" , 7           , "pink"                     , "the number 7 below."       , "Despacito"                , "07-07", "panda"                                                                                , "6"      , 17                    UNION
   SELECT "2019/08/06 11:55:41 PM MDT" , 27          , "blue"                     , "7"                         , "Old Town Road"            , "10-03", "cat"                                                                                  , "1"      , 3                     UNION
   SELECT "2019/08/06 11:57:12 PM MDT" , 2           , "gray"                     , "7"                         , "Bohemian Rhapsody"        , "08-16", "penguins"                                                                             , "6"      , 57                    ;

CREATE TABLE checkboxes AS
   SELECT "2019/08/06 4:19:18 PM MDT" AS time, "False" AS "0", "False" AS "1", "False" AS "2", "False" AS "3", "False" AS "4", "False" AS "5", "False" AS "6", "False" AS "7", "False" AS "8", "False" AS "9", "False" AS "10", "True" AS "2019", "True" AS "9000", "True" AS "9001" UNION
   SELECT "2019/08/06 4:20:15 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 4:21:05 PM MDT"  , "True" , "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:21:53 PM MDT"  , "False", "True" , "False", "False", "False", "False", "True" , "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:22:45 PM MDT"  , "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 4:22:54 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "2019/08/06 4:22:56 PM MDT"  , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:23:20 PM MDT"  , "False", "True" , "False", "False", "True" , "True" , "False", "True" , "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "2019/08/06 4:23:56 PM MDT"  , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:25:05 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:25:54 PM MDT"  , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:27:13 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:28:41 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:29:53 PM MDT"  , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:30:02 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "True" , "False", "True" , "False", "True"  UNION
   SELECT "2019/08/06 4:30:17 PM MDT"  , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:31:10 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:31:47 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:31:57 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:32:30 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:32:49 PM MDT"  , "True" , "True" , "False", "True" , "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 4:33:12 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:33:47 PM MDT"  , "True" , "True" , "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:37:07 PM MDT"  , "False", "True" , "True" , "False", "True" , "True" , "False", "True" , "True" , "False", "True" , "True" , "False", "True"  UNION
   SELECT "2019/08/06 4:39:21 PM MDT"  , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:41:26 PM MDT"  , "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:42:01 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:42:48 PM MDT"  , "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 4:47:30 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "2019/08/06 4:49:56 PM MDT"  , "True" , "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:50:46 PM MDT"  , "False", "False", "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:50:48 PM MDT"  , "True" , "True" , "True" , "False", "True" , "False", "True" , "True" , "False", "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 4:52:02 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 4:52:38 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 4:54:35 PM MDT"  , "False", "False", "False", "True" , "True" , "False", "False", "True" , "True" , "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 4:57:23 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "2019/08/06 4:59:50 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:02:14 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 5:03:53 PM MDT"  , "True" , "True" , "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 5:04:52 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "True" , "True"  UNION
   SELECT "2019/08/06 5:05:40 PM MDT"  , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:13:40 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "2019/08/06 5:13:55 PM MDT"  , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:20:28 PM MDT"  , "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 5:21:03 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 5:24:43 PM MDT"  , "False", "False", "True" , "False", "False", "True" , "True" , "True" , "True" , "False", "True" , "True" , "False", "False" UNION
   SELECT "2019/08/06 5:27:40 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 5:27:47 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "True" , "False", "True"  UNION
   SELECT "2019/08/06 5:29:23 PM MDT"  , "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 5:32:52 PM MDT"  , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:34:22 PM MDT"  , "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "False" UNION
   SELECT "2019/08/06 5:39:08 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:43:06 PM MDT"  , "True" , "False", "False", "True" , "False", "False", "True" , "True" , "True" , "True" , "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 5:50:30 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:51:50 PM MDT"  , "False", "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 5:54:36 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 5:57:31 PM MDT"  , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 6:01:47 PM MDT"  , "False", "False", "False", "True" , "False", "True" , "True" , "False", "True" , "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 6:19:03 PM MDT"  , "True" , "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True" , "True" , "False" UNION
   SELECT "2019/08/06 6:19:24 PM MDT"  , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 6:19:44 PM MDT"  , "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 6:23:10 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 6:35:56 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "2019/08/06 6:42:38 PM MDT"  , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 6:43:56 PM MDT"  , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 6:47:28 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 6:59:14 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 7:02:23 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 7:11:54 PM MDT"  , "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 7:21:10 PM MDT"  , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 7:23:11 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "True"  UNION
   SELECT "2019/08/06 7:25:22 PM MDT"  , "True" , "False", "True" , "False", "True" , "False", "False", "False", "True" , "True" , "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 7:30:00 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 7:31:21 PM MDT"  , "True" , "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "2019/08/06 7:34:46 PM MDT"  , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 7:39:13 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "2019/08/06 8:17:11 PM MDT"  , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 8:29:52 PM MDT"  , "False", "False", "True" , "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "2019/08/06 8:52:25 PM MDT"  , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 9:09:30 PM MDT"  , "True" , "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 9:12:18 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 9:14:27 PM MDT"  , "False", "False", "True" , "False", "True" , "True" , "True" , "False", "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "2019/08/06 9:31:00 PM MDT"  , "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "True" , "False" UNION
   SELECT "2019/08/06 9:33:14 PM MDT"  , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 9:33:47 PM MDT"  , "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "2019/08/06 9:39:40 PM MDT"  , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 9:49:44 PM MDT"  , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 9:58:50 PM MDT"  , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 10:01:57 PM MDT" , "True" , "True" , "False", "False", "False", "True" , "False", "True" , "False", "True" , "True" , "False", "True" , "False" UNION
   SELECT "2019/08/06 10:04:43 PM MDT" , "False", "False", "False", "True" , "True" , "True" , "False", "False", "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 10:17:14 PM MDT" , "False", "False", "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 10:23:42 PM MDT" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 10:26:56 PM MDT" , "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "2019/08/06 10:34:15 PM MDT" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "True" , "True" , "False" UNION
   SELECT "2019/08/06 10:37:02 PM MDT" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "2019/08/06 10:53:09 PM MDT" , "True" , "True" , "True" , "False", "False", "True" , "False", "True" , "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "2019/08/06 10:55:38 PM MDT" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 11:01:55 PM MDT" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "2019/08/06 11:29:42 PM MDT" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "2019/08/06 11:48:10 PM MDT" , "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 11:55:41 PM MDT" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "2019/08/06 11:57:12 PM MDT" , "False", "True" , "True" , "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "True"  ;